import { PageContainer } from "@/components/Common/pageContainer";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar/index";
import Theme from "@/components/Theme";
import { interFont } from "@/constants/fonts";
import { styleConstants } from "@/constants/style";
import "@/styles/globals.css";
import { styled } from "@mui/system";
import type { AppProps } from "next/app";
import Head from "next/head";
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>DPlus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-white.png" />
      </Head>
      <Theme>
        <NavBar />
        <ComponentContainer>
          <PageContainer>
            <Component {...pageProps} />
          </PageContainer>
        </ComponentContainer>
        <Footer />
      </Theme>
    </>
  );
}

const ComponentContainer = styled("div")(({ theme }) => ({
  fontFamily: interFont.style.fontFamily,
  paddingTop: styleConstants.NAV_BAR_HEIGHT,
}));
