import NavBar from "@/components/NavBar/index";
import Theme from "@/components/Theme";
import { interFont } from "@/constants/fonts";
import { styleConstants } from "@/constants/style";
import "@/styles/globals.css";
import { styled } from "@mui/system";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>DPlus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-white.png" />
      </Head>
      <Theme>
        <NavBar />
        <ComponentContainer>
          <Component {...pageProps} />
        </ComponentContainer>
      </Theme>
    </>
  );
}

const ComponentContainer = styled("div")(({ theme }) => ({
  fontFamily: interFont.style.fontFamily,
  paddingTop: styleConstants.NAV_BAR_HEIGHT,
}));
